Make PDF/CDF dropdown a toggle instead
Metaculus/metaculus pull request #1307
Opened 2024-11-07 05:23 UTC by EloiseRosen

For https://github.com/Metaculus/metaculus/issues/479

Looks like after this issue was created the dropdown was updated to include both items. I used the label "Cumulative Distribution Function" as requested in the issue description - let me know if "Cumulative Probability" is preferred.

before:
![toggle_before](https://github.com/user-attachments/assets/b5ce84c3-31b9-463b-a5b2-afa5f28118c4)

after:
https://github.com/user-attachments/assets/94c3332f-74b0-4287-bf80-2db2e75c02fa

2024-11-07 15:09 UTC, lsabor commented
@aseckin Can you approve the design change or make suggestions?

2024-11-08 04:53 UTC, EloiseRosen commented
Realized there's another part of the site that is similar (the aggregation explorer), so added the change to continuous_aggregations_chart.tsx as well

2024-11-08 16:06 UTC, SylvainChevalier commented
That's great, thanks @EloiseRosen!

UI feedback: text takes too much space, especially on mobile. I recommend using `pdf (o ) cdf`, with a hover state that says "pdf = probability density function ; cdf = cumulative density function".

2024-11-08 21:14 UTC, EloiseRosen commented
@SylvainChevalier Good idea, I've shortened the text and added the hover state.

creating a question on mobile (set to iphone 12 pro):
![image](https://github.com/user-attachments/assets/3f806d2a-59eb-4de3-b523-582c0f210481)
the aggregation explorer page on mobile (set to iphone 12 pro):
![image](https://github.com/user-attachments/assets/2050849d-ab3f-437f-b034-809aa4be26ce)
(the aggregation explorer page is a bit tight on mobile in general)

creating a question on desktop, with hovering:
![image](https://github.com/user-attachments/assets/df987031-e82a-4740-9a5a-de3c6e40e1bd)
the aggregation explorer page on desktop, with hovering:
![image](https://github.com/user-attachments/assets/05518fce-e608-4b89-b946-74ae70d5d571)

2024-11-12 11:23 UTC, SylvainChevalier commented
lgtm!

2024-11-12 15:55 UTC, aseckin commented
![image](https://github.com/user-attachments/assets/f9b8fe3c-f69f-47b5-b6c8-ba96b8a8f835)

I made a small adjustment moving the toggle to top-right corner, and adjusted the colors to have better contrast in dark mode. 

One thing I'm concerned with is now that we lost the full abbreviations, novice users might have trouble understanding what these are. It's revisit this and try to add an explainer before merging.

2025-01-08 10:17 UTC, aseckin commented
Revisiting this after a while (sorry about the delay!), I made the following additional changes:
- We implemented a new checkbox "Overlay Current Forecast" so the positioning of this needed to be readjusted
- Added a tooltip for explaining PDF and CDF. 

I'll put this in a live environment for QA and merge as soon as it's cleared.

![pdf-cdf-toggle](https://github.com/user-attachments/assets/555d2965-d677-4fb8-b872-5dd71d076d93)

2025-01-09 10:30 UTC, ncarazon requested changes

2025-01-09 10:30 UTC, ncarazon commented on front_end/src/app/(main)/questions/[id]/components/forecast_maker/continuous_slider.tsx
> +import classNames from "classnames";
We should use `cn` util from `front_end/src/utils/cn.ts`, which will properly handle merging the tailwind classes

2025-01-09 10:30 UTC, ncarazon commented on front_end/src/app/(main)/questions/[id]/components/forecast_maker/continuous_slider.tsx
> +  const shouldHaveMargins = !isGroupQuestion && !isConditionalQuestion;
It would be better to handle the marging specifically where it is needed. As far as I see, we need it only when rendering `ContinuousSlider` inside `ForecastMakerContinuous` component. You could wrap it with `dev` and apply the marging there:

```
      <div className="mt-[-36px] md:mt-[-28px]">
        <ContinuousSlider
          forecast={forecast}
          weights={weights}
          dataset={dataset}
          onChange={(forecast, weight) => {
            setForecast(forecast);
            setWeights(weight);
            setIsDirty(true);
          }}
          overlayPreviousForecast={overlayPreviousForecast}
          setOverlayPreviousForecast={setOverlayPreviousForecast}
          question={question}
          disabled={!canPredict}
        />
      </div>
```

2025-01-09 10:30 UTC, ncarazon commented on front_end/src/components/ui/switch.tsx
> +import classNames from "classnames";
Same note regarding the `cn` util

2025-01-14 13:53 UTC, SylvainChevalier commented
@ncarazon I'd like this to get over the finish line, and looks like @aseckin won't have the bandwidth soon. Could you pick it up?

2025-01-14 15:17 UTC, ncarazon approved these changes

2025-01-14 15:18 UTC, merged